import type { IngestionSource, Prospect, Utility } from './types';

export const UTILITIES: Utility[] = [
  {
    id: 'nyc-dep',
    name: 'NYC Department of Environmental Protection',
    state: 'NY',
    meterStatus: 'AMI mature',
    portalCapability: 'Automated meter readings, portfolio access and usage visibility',
    publicData: 'Benchmarking and building-level city datasets can support prospecting',
    rateSource: 'NYC DEP rate schedule',
  },
  {
    id: 'nj-american-water',
    name: 'New Jersey American Water',
    state: 'NJ',
    meterStatus: 'Mixed / unknown',
    portalCapability: 'Customer portal usage and billing tools',
    publicData: 'Service territory can be resolved through public utility and GIS sources',
    rateSource: 'NJ American Water tariff',
  },
  {
    id: 'veolia-nj',
    name: 'Veolia New Jersey',
    state: 'NJ',
    meterStatus: 'AMI rolling out',
    portalCapability: 'Digital customer account and usage tools vary by service area',
    publicData: 'Municipal and utility service-area records',
    rateSource: 'Veolia NJ tariff',
  },
  {
    id: 'philadelphia-water',
    name: 'Philadelphia Water Department',
    state: 'PA',
    meterStatus: 'AMI mature',
    portalCapability: 'Daily usage visibility and leak notifications',
    publicData: 'City benchmarking and property datasets provide strong enrichment signals',
    rateSource: 'Philadelphia Water rate schedule',
  },
  {
    id: 'pa-american-water',
    name: 'Pennsylvania American Water',
    state: 'PA',
    meterStatus: 'Mixed / unknown',
    portalCapability: 'Customer portal usage tracking',
    publicData: 'Service territory and tariff records',
    rateSource: 'PA American Water tariff',
  },
  {
    id: 'aqua-pa',
    name: 'Aqua Pennsylvania',
    state: 'PA',
    meterStatus: 'AMI rolling out',
    portalCapability: 'ePortal includes billing history and usage visibility in supported areas',
    publicData: 'Utility service territory and public rate filings',
    rateSource: 'Aqua Pennsylvania tariff',
  },
];

export const PROSPECTS: Prospect[] = [
  {
    id: 'algin',
    company: 'Algin Management',
    state: 'NY',
    headquarters: 'New York City',
    portfolioBuildings: 25,
    portfolioUnits: 2500,
    portfolioNote: 'Family-owned NYC owner-operator with a concentrated multifamily portfolio.',
    decisionMaker: 'Operations leadership',
    decisionRole: 'Owner / Property Operations',
    utilityIds: ['nyc-dep'],
    meterOpportunity: 0.72,
    publicDataCoverage: 0.9,
    annualWaterExposure: 320000,
    anomalySignal: 0.56,
    reachability: 0.7,
    stage: 'Qualified',
    confidence: 'Research seed',
    nextAction: 'Resolve portfolio BBLs and benchmark water intensity building by building.',
  },
  {
    id: 'gpg',
    company: 'GPG Management',
    state: 'NY',
    headquarters: 'New York City',
    portfolioBuildings: 100,
    portfolioUnits: 3000,
    portfolioNote: 'Family-owned owner-manager with a large NYC and tri-state operating footprint.',
    decisionMaker: 'Senior operations leadership',
    decisionRole: 'Property Operations / Asset Management',
    utilityIds: ['nyc-dep'],
    meterOpportunity: 0.8,
    publicDataCoverage: 0.92,
    annualWaterExposure: 390000,
    anomalySignal: 0.62,
    reachability: 0.64,
    stage: 'Qualified',
    confidence: 'Research seed',
    nextAction: 'Prioritize highest-use NYC buildings and identify the portfolio operations owner.',
  },
  {
    id: 'legow',
    company: 'Legow Management Company',
    state: 'NJ',
    headquarters: 'New Jersey',
    portfolioBuildings: 35,
    portfolioUnits: 2600,
    portfolioNote: 'Hands-on family owner-manager with dozens of rental communities.',
    decisionMaker: 'Partner / operations leadership',
    decisionRole: 'Ownership / Operations',
    utilityIds: ['nj-american-water', 'veolia-nj'],
    meterOpportunity: 0.88,
    publicDataCoverage: 0.48,
    annualWaterExposure: 300000,
    anomalySignal: 0.5,
    reachability: 0.82,
    stage: 'Qualified',
    confidence: 'Research seed',
    nextAction: 'Map each NJ community to water purveyor and meter capability.',
  },
  {
    id: 'greenzang',
    company: 'Greenzang Properties',
    state: 'PA',
    headquarters: 'Philadelphia',
    portfolioBuildings: 42,
    portfolioUnits: 3500,
    portfolioNote: 'Philadelphia multifamily manager with preventive-maintenance positioning and regional density.',
    decisionMaker: 'Director of Operations',
    decisionRole: 'Operations',
    utilityIds: ['philadelphia-water'],
    meterOpportunity: 0.76,
    publicDataCoverage: 0.88,
    annualWaterExposure: 360000,
    anomalySignal: 0.66,
    reachability: 0.9,
    stage: 'Qualified',
    confidence: 'Research seed',
    nextAction: 'Join portfolio addresses to PWD/benchmarking data and rank suspected waste.',
  },
  {
    id: 'liss',
    company: 'Liss Property Group',
    state: 'PA',
    headquarters: 'Philadelphia region',
    portfolioBuildings: 17,
    portfolioUnits: 2100,
    portfolioNote: 'Regional owner-operator with a concentrated apartment-community portfolio.',
    decisionMaker: 'Operations leadership',
    decisionRole: 'Property Management / Ownership',
    utilityIds: ['philadelphia-water', 'aqua-pa'],
    meterOpportunity: 0.84,
    publicDataCoverage: 0.7,
    annualWaterExposure: 225000,
    anomalySignal: 0.48,
    reachability: 0.8,
    stage: 'Research',
    confidence: 'Research seed',
    nextAction: 'Resolve community service territories and confirm which assets expose interval data.',
  },
];

export const INGESTION_SOURCES: IngestionSource[] = [
  {
    id: 'nyc-benchmarking',
    name: 'NYC Energy & Water Benchmarking',
    geography: 'New York City',
    category: 'Building performance',
    status: 'Ready to wire',
    description: 'Building-level benchmark signal for water intensity and peer comparison.',
  },
  {
    id: 'nyc-dep',
    name: 'NYC DEP Water Data',
    geography: 'New York City',
    category: 'Meter / account',
    status: 'Scaffolded',
    description: 'Public and client-authorized water data paths stay separate by design.',
  },
  {
    id: 'phl-benchmarking',
    name: 'Philadelphia Benchmarking',
    geography: 'Philadelphia',
    category: 'Building performance',
    status: 'Ready to wire',
    description: 'Annual water-performance records for large buildings.',
  },
  {
    id: 'pwd',
    name: 'Philadelphia Water',
    geography: 'Philadelphia',
    category: 'Meter / utility',
    status: 'Scaffolded',
    description: 'AMI-aware usage monitoring path for future authorized accounts.',
  },
  {
    id: 'njdep-gis',
    name: 'NJ Public Water Service GIS',
    geography: 'New Jersey',
    category: 'Utility resolver',
    status: 'Ready to wire',
    description: 'Geospatial service-area resolver from property coordinates to water purveyor.',
  },
  {
    id: 'tariffs',
    name: 'Utility Tariff Registry',
    geography: 'NJ / NY / PA',
    category: 'Rates',
    status: 'Scaffolded',
    description: 'Effective-dated rate records so cost calculations never hard-code a stale tariff.',
  },
];
