import type { SourceCatalogEntry } from './types';

/**
 * These are discovery references, not live connectors. Every imported record
 * still needs a source reference, retrieval date, and field-level status.
 */
export const SOURCE_CATALOG: SourceCatalogEntry[] = [
  {
    id: 'nyc-ll84-water',
    name: 'NYC building energy & water disclosure (LL84)',
    markets: ['NY'],
    kind: 'Official open data',
    access: 'Public download/API',
    url: 'https://data.cityofnewyork.us/Environment/NYC-Building-Energy-and-Water-Data-Disclosure-for-/5zyy-y8am/explore',
    description: 'Public building-level disclosure. Confirm matching, reporting year, and estimated-data flags before using it.',
  },
  {
    id: 'nyc-dep-records',
    name: 'NYC DEP water & sewer record requests',
    markets: ['NY'],
    kind: 'Official program reference',
    access: 'Manual review required',
    url: 'https://www.nyc.gov/site/dep/about/request-records.page',
    description: 'Official records pathway. Do not automate authenticated or restricted requests.',
  },
  {
    id: 'nys-dec-water-service',
    name: 'NYS DEC public water supply service areas',
    markets: ['NY'],
    kind: 'Official GIS',
    access: 'Public download/API',
    url: 'https://gisservices.dec.ny.gov/arcgis/rest/services/der/der_viewer/MapServer/4',
    description: 'Published mapping aid. A map result is not proof of a property account, service status, or customer authorization.',
  },
  {
    id: 'nyc-water-board-rates',
    name: 'NYC Water Board rates and regulations',
    markets: ['NY'],
    kind: 'Official rate reference',
    access: 'Manual review required',
    url: 'https://www.nyc.gov/site/nycwaterboard/rates/rates-regulations.page',
    description: 'Effective-dated rate reference. Review the published schedule before storing any tariff components.',
  },
  {
    id: 'phl-benchmarking',
    name: 'Philadelphia large-building benchmarking',
    markets: ['PA'],
    kind: 'Official open data',
    access: 'Public download/API',
    url: 'https://opendataphilly.org/datasets/large-building-energy-benchmarking-data/',
    description: 'Public annual benchmarking; water values are self-reported and require source-aware interpretation.',
  },
  {
    id: 'phl-water-rates',
    name: 'Philadelphia Water Department rate reference',
    markets: ['PA'],
    kind: 'Official rate reference',
    access: 'Manual review required',
    url: 'https://water.phila.gov/water-utility/',
    description: 'Reference only. Add an effective-dated tariff record after review; Puma never supplies a default rate.',
  },
  {
    id: 'phl-ami-program',
    name: 'Philadelphia Water Department AMI project',
    markets: ['PA'],
    kind: 'Official program reference',
    access: 'Manual review required',
    url: 'https://water.phila.gov/projects/ami/',
    description: 'Describes a utility program and customer portal path. It does not prove a specific property has an active account, meter, or authorized feed.',
  },
  {
    id: 'njdep-purveyor',
    name: 'NJDEP community water purveyor service areas',
    markets: ['NJ'],
    kind: 'Official GIS',
    access: 'Public download/API',
    url: 'https://mapsdep.nj.gov/arcgis/rest/services/Features/Utilities/MapServer/13',
    description: 'Service-area layer for public community water purveyors. Match a property spatially and preserve the query date.',
  },
  {
    id: 'njgin-parcels',
    name: 'New Jersey Geographic Information Network',
    markets: ['NJ'],
    kind: 'Official GIS',
    access: 'Public download/API',
    url: 'https://www.nj.gov/njgin/',
    description: 'Use for parcel and geography research; verify each underlying layer and publication date.',
  },
  {
    id: 'nj-bpu-water-tariffs',
    name: 'New Jersey BPU water tariffs',
    markets: ['NJ'],
    kind: 'Official rate reference',
    access: 'Manual review required',
    url: 'https://www.nj.gov/bpu/bpu/about/divisions/water/tariffs_water.html',
    description: 'Investor-owned utility tariff reference. It is not complete municipal coverage and is not a live billing connector.',
  },
  {
    id: 'pa-dep-emappa',
    name: 'Pennsylvania DEP eMapPA public layers',
    markets: ['PA'],
    kind: 'Official GIS',
    access: 'Public download/API',
    url: 'https://gis.dep.pa.gov/depgisprd/rest/services/emappa/eMapPA_External/FeatureServer',
    description: 'Published geographic reference. Preserve the source layer and query date; do not expose restricted system details or infer account access.',
  },
  {
    id: 'pa-american-rates',
    name: 'Pennsylvania American Water rate reference',
    markets: ['PA'],
    kind: 'Official rate reference',
    access: 'Manual review required',
    url: 'https://www.amwater.com/paaw/customer-service-billing/your-water-and-wastewater-rates',
    description: 'Operating-company rate reference only. Confirm a property service relationship and effective date before using a tariff.',
  },
];
